print ('Qual é seu nome?')
nome = input ('Nome: ')
print('Seja bem vindo '+ nome + '!')

print ('Me fale o dia mes e ano que nasceu')
dia = input ('Dia: ')
mes = input ('Mes: ')
ano = input ('Ano: ')
print ('Você nasceu no dia '+ dia + ' de ' + mes + ' de ' + ano + '. Correto?')

print ('Me diga dois numeros')
n1 = input ('Primeiro numero: ')
n2 = input ('Segundo numero: ')
soma = int(n1) + int(n2)
print ('A soma é: ' + str(soma))